sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  xsens_imu_link:
    x: 0.0
    y: 0.0
    z: 0.08
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# ************************************************************************************
# lidar: トピックの中身を見て確認する
# xsens: mtmanagerで確認
# ************************************************************************************